---
/detect_lane:
  ros__parameters:
    detect:
      lane:
        white:
          hue_h: 179
          hue_l: 0
          lightness_h: 255
          lightness_l: 190
          saturation_h: 76
          saturation_l: 0
        yellow:
          hue_h: 123
          hue_l: 10
          lightness_h: 255
          lightness_l: 193
          saturation_h: 255
          saturation_l: 115
